name: CI/CD
on:
  push:
    branches: [master, staging, qa, feature/**]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Checkout Project
        uses: actions/checkout@v2
        
      - name: Install dependecies
        run: sh install-dependecies.sh

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Install dependecies
        run: pip3 install boto3 | sh install-dependecies.sh
      
      - run: pytest -s
    
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: qa
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Checkout Project
        uses: actions/checkout@v2
      
      - name: zip-files
        uses: papeloto/action-zip@v1
        with:
          files: models psycopg2 utils lambda.py
          dest: result.zip
    
      - name: Install dependecies
        run: sh install-dependecies.sh
      
      - name: deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: test1
          zip_file: result.zip
          memory_size: 128
          timeout: 10
          handler: lambda.lambda_handler
          role: arn:aws:iam::510807795258:role/service-role/test1-role-7l0hsyjp
          runtime: python3.7
  